
package com.dhatvibs.entity;

public enum OnboardingStage {
    PHONE_VERIFICATION,
    APP_PERMISSIONS,
    SELECT_LOCATION,
    SELECT_VEHICLE,
    PERSONAL_INFO,
    SELFIE,
    AADHAAR,
    PAN_UPLOAD,
    DL_UPLOAD,
    KYC_SUBMITTED,
    KYC_APPROVAL_PENDING,
    KYC_APPROVED,
    COMPLETED
}
