spring.application.name=DeliveryPartner 

# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d5s4incoud1c739198qg-a.oregon-postgres.render.com:5432/deliveryapp_x6e0
spring.datasource.username=rider_user
spring.datasource.password=sEM9MNYcU30Nzbd28Brtr716BeXwlXOQ

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Azure Blob Storage
azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.storage.container-name=delivery-partner-documents




# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

