spring.application.name=DeliveryPartner 

# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d57m4ljuibrs73a8f0f0-a.oregon-postgres.render.com:5432/deliverypartner
spring.datasource.username=deliverypartner_user
spring.datasource.password=O4EVwbg0xQEgojS2HEsYJwjuxw9jEUli

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Azure Blob Storage
#azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
#azure.storage.container-name=javadeliverypartner

#azure.storage.container-name=JavaDeliveryPartner


# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

